### ISSUE TITLE
unhide file/directory

### ISSUE THREAD

**Issue by mdinesh-kumar** [Andr3as/Codiad-Ignore#2]
Not able to unhide file or folder which are ignored. How to revoke ignored file or directory?

**Comment by Andr3as** [comment]
You have to remove the rule in the settings.
<img width="855" alt="screenshot" src="https://cloud.githubusercontent.com/assets/4389878/19276941/50d232a0-8fd8-11e6-9398-4944161104c3.png">

**Comment by Andr3as** [comment]
Please reopen if required
